### ISSUE TITLE
Validate Jira 9 release - EAP

### ISSUE THREAD

**Issue by knoppanthony** [atlassian-labs/msteams-jira-server-addon#6]
EAP is here https://www.atlassian.com/software/jira/download-eap?_ga=2.227824606.291373623.1647880020-2043599991.1647029962

Looking for a smoke test to ensure plugin is still compatible. No known big backwards breaking changes.

**Comment by Hensorskyy** [comment]
Hi @knoppanthony 
We will perform the checks and let you know.

**Comment by Hensorskyy** [comment]
@knoppanthony I have tested the plugin and can confirm that it's fully compatible with the Jira EAP version. Please note that users will have to install it manually as the version is not set in the marketplace listing. The latest version of the addon can be downloaded from [here](https://github.com/atlassian-labs/msteams-jira-server-addon/actions/runs/1853494834)

**Comment by sylwiamikolajczuk** [comment]
Hi team, do you have any ETA on bumping the compatibility of this plugin on MPAC? Thanks!
